# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-22 02:17
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_auto_20161021_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, default=b'#CF1425', null=True),
        ),
    ]
