# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-22 03:10
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_auto_20161021_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='display_author',
            field=models.CharField(blank=True, default=b'anonymous coward', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, default=b'#88340F', null=True),
        ),
    ]
