# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-10-22 04:23
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0017_auto_20161021_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='display_author',
            field=models.CharField(default=b'anonymous coward', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, default=b'#A767A2', null=True),
        ),
    ]
